# example profiles.yml file
defaults:
  outputs:
    dev:
      type: postgres
      server: localhost
      port: 3306
      schema: analytics
      username: 'root'
      password: 'root'

  target: dev
